name: spaCy Python Package Artifactory Publish

on: 
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  ARTIFACTORY_PULL_URL: artifactory.riotinto.com/artifactory/api/pypi/riotinto-pypi/simple
  ARTIFACTORY_PUSH_URL: https://artifactory.riotinto.com/artifactory/api/pypi/rio-innersource-pypi
  SPACY_COMPATIBILITY_URL: https://raw.githubusercontent.com/explosion/spacy-models/master/compatibility.json

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env:
          CIBW_SOME_OPTION: value
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - name: Upload wheels as Github artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload source dist as Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload-compatibility-file-to-artifactory:
    name: Upload compatibility JSON file to artifactory
    runs-on: ubuntu-latest
    steps:
      - name: Download JSON
        run: curl $SPACY_COMPATIBILITY_URL -o compatibility.json

      - name: Upload JSON
        run: |
          curl -v -X PUT \
          --upload-file compatibility.json \
          "https://${{ secrets.GHA_ARTIFACTORY_USERNAME}}:${{ secrets.GHA_ARTIFACTORY_PASSWORD }}@artifactory.riotinto.com/artifactory/rio-innersource-pypi/spacy/compatibility.json"

  upload-to-artifactory:
    name: Upload artifacts to artifactory
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Upload to Artifactory
        run: |
          twine upload --repository-url $ARTIFACTORY_PUSH_URL dist/* -u${{ secrets.GHA_ARTIFACTORY_USERNAME }} -p${{ secrets.GHA_ARTIFACTORY_PASSWORD }}
